version: '3'
services:
    postgres:
        image: postgres:14.1-alpine
        container_name: postgres
        restart: always
        environment:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: JWT-test
        networks: 
          - new_network
        ports:
          - 6432:5432

    adminer:
      image: adminer
      container_name: adminer
      restart: always
      ports:
        - 8090:8080
      depends_on:
        - postgres
      networks: 
        - new_network

    backend:
        container_name: backend
        build:
            context: ./src
            dockerfile: Dockerfile
        depends_on:
            - postgres
        volumes:
            - ./src:/usr/src
        networks:
            - new_network
        ports:
            - 10001:5000
        environment:
            DATABASE_HOST: postgres
            DATABASE_PORT: 5432
            DATABASE_NAME: JWT-test

    nginx:
      image: 1.23.3-alpine
      container_name: production_nginx
      build:
        context: ./proxy
        dockerfile: Dockerfile
      volumes:
        - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      depends_on:
        - backend
      networks:
        - new_network
      ports:
        - 6060:60
        - 443:443
    
                
networks:
    new_network:
        external: False